
#spring:
#  data:
#    redis:
#      port: 6379
#      host: localhost

#jwt:
#  secret:
#    key: KWEN@OJM%I@JKQJASLJAHWUJNBZHSLKN

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/imguru?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
#
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true

spring:
  datasource:
    url: jdbc:mariadb://121.134.218.34:13306/imguru
    driver-class-name: org.mariadb.jdbc.Driver
    username: imguru
    password: imguru1!

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true