
spring:
  datasource:
    url: ENC(+vix7/vcxgyLJ3iQgL9hM7VumtxjyNAq1A5OJbi33KJBIh4bRMhIRfcfHKFoGTMs)
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(/qJhhyhJn/yLytTuvftGwg==)
    password: ENC(OOi5zWipqFzEB2zy14X76YQtFr8Mdgr9)
  data:
    redis:
      port: 9379
      host: ENC(V5uPqa//XY0jNugHz/HzE5Uxtl8h+FQu)

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret:
    key: KWEN@OJM%I@JKQJASLJAHWUJNBZHSLKN

