
spring:
  datasource:
    url: jdbc:mariadb://121.134.218.34:13306/imguru
    driver-class-name: org.mariadb.jdbc.Driver
    username: imguru
    password: imguru1!
  data:
    redis:
      port: 6379
      host: localhost

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret:
    key: KWEN@OJM%I@JKQJASLJAHWUJNBZHSLKN

jasypt:
  encryptor:
    password: yourEncryptionPassword
